//go:build test

package wscli

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"
)

func TestGenerateWindshiftMDCorrectness(t *testing.T) {
	previousVersion := version
	version = "0.8.2-test"
	t.Cleanup(func() { version = previousVersion })

	fromOpen := 1
	statuses := []Status{
		{ID: 1, Name: "Open", CategoryName: "To Do", IsDefault: true},
		{ID: 3, Name: "Done", CategoryName: "Done", IsCompleted: true},
	}
	transitions := []Transition{
		{ToStatusID: 1, ToStatus: &StatusSummary{ID: 1, Name: "Open"}},
		{FromStatusID: &fromOpen, ToStatusID: 3, ToStatus: &StatusSummary{ID: 3, Name: "Done"}},
	}
	generatedAt := time.Date(2026, time.July, 21, 8, 30, 0, 0, time.UTC)

	for _, workspaceKey := range []string{"WI", "ACME"} {
		t.Run(workspaceKey, func(t *testing.T) {
			doc := generateWindshiftMD(
				&Workspace{Key: workspaceKey, Name: "Example"},
				statuses,
				[]ItemType{{ID: 1, Name: "Task"}},
				transitions,
				map[string]string{"done": "3"},
				generatedAt,
			)

			for _, want := range []string{
				"Generated by `ws 0.8.2-test` at 2026-07-21T08:30:00Z",
				`ws page search "keyword or phrase"`,
				"Search titles and content",
				"ws page labels <page-id>",
				"ws skill ls",
				"ws skill get <skill-id>",
				"Follow user and repository instructions before this guide.",
				workspaceKey + "-123",
				"| `done` | 3 | `ws task move <KEY-123> done` |",
			} {
				if !strings.Contains(doc, want) {
					t.Errorf("generated document missing %q", want)
				}
			}
			if lines := strings.Count(doc, "\n"); lines > 140 {
				t.Errorf("generated guide is too long for consumer-agent context: %d lines", lines)
			}
			if words := len(strings.Fields(doc)); words > 750 {
				t.Errorf("generated guide is too verbose for consumer-agent context: %d words", words)
			}
			for _, internalDetail := range []string{
				"item_links",
				"Scopes & Capabilities",
				"default mint",
				"parent_id",
				"~/.config/ws",
			} {
				if strings.Contains(doc, internalDetail) {
					t.Errorf("generated consumer guide exposes internal detail %q", internalDetail)
				}
			}
			if strings.Contains(doc, "ws page-label labels") {
				t.Error("generated document contains obsolete page-label assignment command")
			}
			if workspaceKey != "WI" && strings.Contains(doc, "WI-") {
				t.Error("non-WI document contains a hard-coded WI item key")
			}

			assertDocumentedCommandsExist(t, doc)
		})
	}
}

func TestWriteWindshiftMDFailsWhenTransitionsAreUnavailable(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/rest/api/v1/workflows/7/transitions" {
			t.Errorf("unexpected request path: %s", r.URL.Path)
		}
		http.Error(w, "transitions unavailable", http.StatusServiceUnavailable)
	}))
	t.Cleanup(server.Close)

	client := &Client{baseURL: server.URL, token: "test", httpClient: server.Client()}
	path := filepath.Join(t.TempDir(), "WINDSHIFT.md")
	err := writeWindshiftMD(client, &WorkspaceContext{
		Workspace: &Workspace{Key: "ACME", Name: "Example"},
		Workflows: []Workflow{{ID: 7, Name: "Default", IsDefault: true}},
	}, map[string]string{}, path)
	if err == nil || !strings.Contains(err.Error(), `failed to get transitions for default workflow "Default"`) {
		t.Fatalf("expected visible transition lookup failure, got %v", err)
	}
	if _, statErr := os.Stat(path); !os.IsNotExist(statErr) {
		t.Fatalf("failed refresh must not write a falsely complete document; stat error = %v", statErr)
	}
}

// assertDocumentedCommandsExist treats the Cobra tree as the source of truth.
// It scans every shell-example line beginning with `ws`, walks literal command
// tokens until it reaches a runnable leaf, and fails when the document names an
// unknown or incomplete subcommand such as the old `ws page-label labels`.
func assertDocumentedCommandsExist(t *testing.T, doc string) {
	t.Helper()
	for _, line := range strings.Split(doc, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "ws ") {
			continue
		}
		fields := strings.Fields(line)
		cmd := rootCmd
		for _, token := range fields[1:] {
			if strings.HasPrefix(token, "-") || strings.HasPrefix(token, "<") {
				break
			}
			child := directChild(cmd, token)
			if child == nil {
				if cmd.HasSubCommands() {
					t.Errorf("documented command line %q names unknown subcommand %q under %q", line, token, cmd.CommandPath())
				}
				break
			}
			cmd = child
		}
		if cmd == rootCmd || (cmd.HasSubCommands() && !cmd.Runnable()) {
			t.Errorf("documented command line %q does not resolve to a runnable command", line)
		}
	}
}

func directChild(parent *cobra.Command, token string) *cobra.Command {
	for _, child := range parent.Commands() {
		if child.Name() == token {
			return child
		}
		for _, alias := range child.Aliases {
			if alias == token {
				return child
			}
		}
	}
	return nil
}
