package actioncatalog_test

import (
	"encoding/json"
	"strings"
	"testing"

	"windshift/internal/models"
	"windshift/internal/services/actioncatalog"
)

// TestCatalogBuilds is the smoke test — Default() panics on a build error,
// so just calling it here is enough to catch a regression where a config
// struct can't be reflected by the jsonschema library.
func TestCatalogBuilds(t *testing.T) {
	cat := actioncatalog.Default()
	if len(cat.Nodes()) == 0 {
		t.Fatal("catalog has no nodes")
	}
	if len(cat.Triggers()) == 0 {
		t.Fatal("catalog has no triggers")
	}
}

// TestNodeTypeCatalogCoverage is the drift detector. Build() returns an
// error when a constant in AllActionNodeTypes has no metadata, so this
// test asserts the opposite direction too: every ActionNodeType constant
// declared in internal/models must appear in AllActionNodeTypes. Adding
// a new ActionNodeXxx constant without updating the list fails this test.
//
// We can't reflect over a const block, so we hardcode the known list and
// fail if it diverges from what the catalog covers. This keeps the catalog
// itself unaware of the constants, which is the source of truth.
func TestNodeTypeCatalogCoverage(t *testing.T) {
	// Pull every constant via reflection on the models package by listing
	// the known set. If this list goes stale (someone adds a new node
	// constant), the catalog Build() drift check will fail first; if they
	// add the catalog entry but forget the list here, this fails to make
	// the two-list ergonomics explicit.
	wantNodeTypes := []models.ActionNodeType{
		models.ActionNodeTrigger,
		models.ActionNodeSetField,
		models.ActionNodeSetStatus,
		models.ActionNodeAddComment,
		models.ActionNodeNotifyUser,
		models.ActionNodeCondition,
		models.ActionNodeUpdateAsset,
		models.ActionNodeCreateAsset,
		models.ActionNodeRoundRobinAssign,
		models.ActionNodeAIExtract,
		models.ActionNodeAIAgent,
		models.ActionNodeContainerRun,
		models.ActionNodeHTTPRequest,
		models.ActionNodeTransitionItem,
		models.ActionNodeRelatedItems,
		models.ActionNodeCreateMilestone,
	}

	got := map[models.ActionNodeType]bool{}
	for _, nt := range actioncatalog.AllActionNodeTypes {
		got[nt] = true
	}
	for _, want := range wantNodeTypes {
		if !got[want] {
			t.Errorf("AllActionNodeTypes is missing %q — add it (and a corresponding registerNode in catalog.go)", want)
		}
	}

	cat := actioncatalog.Default()
	for _, nt := range wantNodeTypes {
		if cat.Node(nt) == nil {
			t.Errorf("catalog has no metadata for node type %q", nt)
		}
	}
}

// TestTriggerTypeCatalogCoverage is the trigger counterpart.
func TestTriggerTypeCatalogCoverage(t *testing.T) {
	wantTriggerTypes := []models.ActionTriggerType{
		models.ActionTriggerStatusTransition,
		models.ActionTriggerItemCreated,
		models.ActionTriggerItemUpdated,
		models.ActionTriggerItemLinked,
		models.ActionTriggerManual,
		models.ActionTriggerSCMTagCreated,
		models.ActionTriggerSCMReleaseBranchCreated,
	}

	cat := actioncatalog.Default()
	for _, tt := range wantTriggerTypes {
		if cat.Trigger(tt) == nil {
			t.Errorf("catalog has no metadata for trigger type %q", tt)
		}
	}
}

// TestNodeConfigSchemaRoundTrip exercises the validator against a valid
// example config per node type. The expected example is generated by
// JSON-marshalling a zero-valued config struct, so this only catches
// "the schema can't accept the zero value" — but that's the case that
// matters: clients use catalog defaults as a starting point and the
// editor must be able to save them unchanged.
func TestNodeConfigSchemaRoundTrip(t *testing.T) {
	cat := actioncatalog.Default()

	type sample struct {
		typ models.ActionNodeType
		cfg any
	}
	// One example per node type. Empty `{}` is fine for nodes whose
	// schema is permissive; nodes with required fields use a minimal
	// shape that matches the documented contract.
	cases := []sample{
		{models.ActionNodeTrigger, map[string]any{}},
		{models.ActionNodeSetField, models.SetFieldNodeConfig{FieldName: "status_id", Value: "1"}},
		{models.ActionNodeSetStatus, models.SetStatusNodeConfig{StatusID: 1}},
		{models.ActionNodeAddComment, models.AddCommentNodeConfig{Content: "hello"}},
		{models.ActionNodeNotifyUser, models.NotifyUserNodeConfig{Recipients: []string{"assignee"}, Message: "ping"}},
		{models.ActionNodeCondition, models.ConditionNodeConfig{FieldName: "status_id", Operator: "eq", Value: "1"}},
		{models.ActionNodeUpdateAsset, models.UpdateAssetNodeConfig{SourceFieldID: "cf_1", AssetSetID: 1, AssetTypeID: 1}},
		{models.ActionNodeCreateAsset, models.CreateAssetNodeConfig{AssetSetID: 1, AssetTypeID: 1, Title: "x"}},
		{models.ActionNodeRoundRobinAssign, models.RoundRobinAssignNodeConfig{TeamID: 1, SkipOnLeaveMembers: true, UseLeaveSubstitutes: true}},
		{models.ActionNodeAIExtract, models.AIExtractNodeConfig{Prompt: "x", InputField: "i", OutputField: "o", CapabilityID: 1}},
		{models.ActionNodeAIAgent, models.AIAgentNodeConfig{Prompt: "x", OutputField: "o", CapabilityID: 1}},
		{models.ActionNodeContainerRun, models.ContainerRunNodeConfig{CapabilityID: 1, OutputField: "o", TimeoutSecs: 60}},
		{models.ActionNodeHTTPRequest, models.HTTPRequestNodeConfig{Method: "GET", URLTemplate: "https://x", OutputField: "o"}},
		{models.ActionNodeTransitionItem, models.TransitionItemNodeConfig{}},
		{models.ActionNodeRelatedItems, models.RelatedItemsNodeConfig{Relation: "descendants"}},
		{models.ActionNodeCreateMilestone, map[string]any{"upsert_key_template": "{{ref.short}}"}},
	}

	for _, c := range cases {
		t.Run(string(c.typ), func(t *testing.T) {
			raw, err := json.Marshal(c.cfg)
			if err != nil {
				t.Fatalf("marshal sample: %v", err)
			}
			def := actioncatalog.ActionDefinition{
				Name:          "x",
				TriggerType:   models.ActionTriggerManual,
				TriggerConfig: "{}",
				Nodes: []models.ActionNode{
					{ID: 1, NodeType: models.ActionNodeTrigger, NodeConfig: "{}"},
					{ID: 2, NodeType: c.typ, NodeConfig: string(raw)},
				},
				Edges: []models.ActionEdge{
					{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"},
				},
			}
			// trigger-only sample uses node 1 alone, no second node
			if c.typ == models.ActionNodeTrigger {
				def.Nodes = def.Nodes[:1]
				def.Edges = nil
			}
			errs := actioncatalog.Validate(cat, def, 0, nil)
			if len(errs) != 0 {
				t.Fatalf("expected no validation errors for %s, got:\n%v", c.typ, errs)
			}
		})
	}
}

// TestValidateRejectsBrokenShapes covers the negative cases: unknown
// trigger, unknown node type, invalid JSON config, dangling edge.
func TestValidateAcceptsEditorAuthoredShapes(t *testing.T) {
	cat := actioncatalog.Default()
	trigger := models.ActionNode{ID: 1, NodeType: models.ActionNodeTrigger, NodeConfig: `{}`}
	edge := models.ActionEdge{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"}

	cases := []struct {
		name          string
		triggerType   models.ActionTriggerType
		triggerConfig string
		node          models.ActionNode
	}{
		{
			name:          "set_field display props from UI",
			triggerType:   models.ActionTriggerManual,
			triggerConfig: `{}`,
			node: models.ActionNode{ID: 2, NodeType: models.ActionNodeSetField,
				NodeConfig: `{"field_name":"description","field_display_name":"Description","value":"x","value_display_name":"X"}`},
		},
		{
			name:          "notify_user recipient_type from UI",
			triggerType:   models.ActionTriggerManual,
			triggerConfig: `{}`,
			node: models.ActionNode{ID: 2, NodeType: models.ActionNodeNotifyUser,
				NodeConfig: `{"recipient_type":"assignee","recipients":[],"message":"hi","include_link":true}`},
		},
		{
			name:          "related_items palette default",
			triggerType:   models.ActionTriggerManual,
			triggerConfig: `{}`,
			node:          models.ActionNode{ID: 2, NodeType: models.ActionNodeRelatedItems, NodeConfig: `{"relation":"descendants","cross_workspace":false}`},
		},
		{
			name:          "transition_item palette default",
			triggerType:   models.ActionTriggerManual,
			triggerConfig: `{}`,
			node:          models.ActionNode{ID: 2, NodeType: models.ActionNodeTransitionItem, NodeConfig: `{"target":{"mode":"matching_terminal"},"skip_if_already_matching":true}`},
		},
		{
			name:          "round_robin runtime config",
			triggerType:   models.ActionTriggerManual,
			triggerConfig: `{}`,
			node: models.ActionNode{ID: 2, NodeType: models.ActionNodeRoundRobinAssign,
				NodeConfig: `{"team_id":1,"skip_on_leave_members":true,"use_leave_substitutes":true}`},
		},
		{
			name:          "create_milestone SCM template config",
			triggerType:   models.ActionTriggerSCMTagCreated,
			triggerConfig: `{}`,
			node: models.ActionNode{ID: 2, NodeType: models.ActionNodeCreateMilestone,
				NodeConfig: `{"name_template":"Release {{ref.short}}","upsert_key_template":"{{ref.short}}","status_on_branch":"planning","status_on_tag":"in-progress","attach_release_on_tag":true,"attach_commit_issues":true}`},
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			errs := actioncatalog.Validate(cat, actioncatalog.ActionDefinition{
				Name:          "x",
				TriggerType:   c.triggerType,
				TriggerConfig: c.triggerConfig,
				Nodes:         []models.ActionNode{trigger, c.node},
				Edges:         []models.ActionEdge{edge},
			}, 0, nil)
			if len(errs) != 0 {
				t.Fatalf("expected editor-authored shape to validate, got %v", errs)
			}
		})
	}

	t.Run("manual trigger accepts cascade flag", func(t *testing.T) {
		errs := actioncatalog.Validate(cat, actioncatalog.ActionDefinition{
			Name:          "x",
			TriggerType:   models.ActionTriggerManual,
			TriggerConfig: `{"respond_to_cascades":true}`,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger, NodeConfig: `{"respond_to_cascades":true}`},
			},
		}, 0, nil)
		if len(errs) != 0 {
			t.Fatalf("expected manual cascade flag to validate, got %v", errs)
		}
	})
}

func TestValidateRejectsBrokenShapes(t *testing.T) {
	cat := actioncatalog.Default()

	t.Run("unknown trigger type", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerType("not_a_real_trigger"),
			Nodes:       []models.ActionNode{{ID: 1, NodeType: models.ActionNodeTrigger}},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeUnknownTriggerType) {
			t.Fatalf("expected unknown_trigger_type, got %v", errs)
		}
	})

	t.Run("unknown node type", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{ID: 2, NodeType: models.ActionNodeType("nope")},
			},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeUnknownNodeType) {
			t.Fatalf("expected unknown_node_type, got %v", errs)
		}
	})

	t.Run("invalid config JSON", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{ID: 2, NodeType: models.ActionNodeSetField, NodeConfig: `{not-json`},
			},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeInvalidConfigJSON) {
			t.Fatalf("expected invalid_config_json, got %v", errs)
		}
	})

	t.Run("edge to missing node", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
			},
			Edges: []models.ActionEdge{
				{SourceNodeID: 1, TargetNodeID: 999, EdgeType: "default"},
			},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeUnknownNodeID) {
			t.Fatalf("expected unknown_node_id, got %v", errs)
		}
	})

	t.Run("multiple non-trigger nodes without edges", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{ID: 2, NodeType: models.ActionNodeSetField, NodeConfig: `{"field_name":"x","value":"y"}`},
				{ID: 3, NodeType: models.ActionNodeAddComment, NodeConfig: `{"content":"x"}`},
			},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeAmbiguousFlow) {
			t.Fatalf("expected ambiguous_flow, got %v", errs)
		}
	})

	t.Run("name missing", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{TriggerType: models.ActionTriggerManual}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeRequired) {
			t.Fatalf("expected required code, got %v", errs)
		}
	})

	t.Run("http_request rejects sensitive Headers map", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{
					ID:       2,
					NodeType: models.ActionNodeHTTPRequest,
					NodeConfig: `{"method":"GET","url_template":"https://x","output_field":"o","capability_id":1,` +
						`"headers":{"Authorization":"Bearer LEAKED-FROM-NODE-CONFIG"}}`,
				},
			},
			Edges: []models.ActionEdge{{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"}},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeInvalidConfig) {
			t.Fatalf("expected invalid_config for sensitive node header, got %v", errs)
		}
		for _, e := range errs {
			if strings.Contains(e.Message, "LEAKED-FROM-NODE-CONFIG") {
				t.Errorf("validator leaked plaintext token into error: %v", e)
			}
		}
	})

	t.Run("http_request allows non-sensitive Headers", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{
					ID:       2,
					NodeType: models.ActionNodeHTTPRequest,
					NodeConfig: `{"method":"GET","url_template":"https://x","output_field":"o","capability_id":1,` +
						`"headers":{"Accept":"application/json","X-Request-Id":"abc"}}`,
				},
			},
			Edges: []models.ActionEdge{{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"}},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if errs.Has(actioncatalog.CodeInvalidConfig) {
			t.Fatalf("non-sensitive headers must be accepted: %v", errs)
		}
	})

	t.Run("ai_agent max_steps over cap", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{
					ID:       2,
					NodeType: models.ActionNodeAIAgent,
					NodeConfig: `{"prompt":"hello","input_fields":["title"],"tools":[],` +
						`"max_steps":51,"output_field":"out","capability_id":1}`,
				},
			},
			Edges: []models.ActionEdge{{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"}},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeInvalidConfig) {
			t.Fatalf("expected invalid_config for max_steps over cap, got %v", errs)
		}
		var foundPath bool
		for _, e := range errs {
			if strings.Contains(e.Path, "max_steps") {
				foundPath = true
			}
		}
		if !foundPath {
			t.Errorf("expected error path to point at max_steps; got %v", errs)
		}
	})

	t.Run("ai_agent max_steps at cap accepted", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:        "x",
			TriggerType: models.ActionTriggerManual,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger},
				{
					ID:       2,
					NodeType: models.ActionNodeAIAgent,
					NodeConfig: `{"prompt":"hello","input_fields":["title"],"tools":[],` +
						`"max_steps":50,"output_field":"out","capability_id":1}`,
				},
			},
			Edges: []models.ActionEdge{{SourceNodeID: 1, TargetNodeID: 2, EdgeType: "default"}},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		// caps resolver is nil so unknown_capability is skipped — we only
		// care that no invalid_config fires for max_steps.
		for _, e := range errs {
			if strings.Contains(e.Path, "max_steps") {
				t.Fatalf("did not expect max_steps error at the cap, got %v", errs)
			}
		}
	})

	t.Run("trigger config wrong shape", func(t *testing.T) {
		// status_transition config has an int field; pass a string.
		def := actioncatalog.ActionDefinition{
			Name:          "x",
			TriggerType:   models.ActionTriggerStatusTransition,
			TriggerConfig: `{"from_status_id": "not an int"}`,
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if !errs.Has(actioncatalog.CodeInvalidConfig) {
			t.Fatalf("expected invalid_config, got %v", errs)
		}
		// Path should pinpoint the bad field
		var found bool
		for _, e := range errs {
			if strings.HasPrefix(e.Path, "trigger_config") {
				found = true
			}
		}
		if !found {
			t.Errorf("expected trigger_config path; got %v", errs)
		}
	})

	t.Run("trigger node accepts status transition filters", func(t *testing.T) {
		def := actioncatalog.ActionDefinition{
			Name:          "x",
			TriggerType:   models.ActionTriggerStatusTransition,
			TriggerConfig: `{"to_status_id": 3}`,
			Nodes: []models.ActionNode{
				{ID: 1, NodeType: models.ActionNodeTrigger, NodeConfig: `{"to_status_id": 3}`},
			},
		}
		errs := actioncatalog.Validate(cat, def, 0, nil)
		if len(errs) != 0 {
			t.Fatalf("expected trigger node status filter to validate, got %v", errs)
		}
	})
}
